### ISSUE TITLE
Crash on app search results

### ISSUE THREAD

**Issue by RodionGodo** [ComputerElite/Rift-downgrader#1]
For whatever reason API returns the same app "DeoVR Video Player" twice (at least), and the program crashes with  System.ArgumentException: An item with the same key has already been added.

The log is attached.
[Log.log](https://github.com/ComputerElite/Rift-downgrader/files/7505982/Log.log)

**Comment by ComputerElite** [comment]
Interesting. I'll implement a fix for that

**Comment by ComputerElite** [comment]
Seems like it had to do with the online cache I have. idk why but I think I also forgot to implement something that checks if the app from the cache is already existing. idk why this happened in the first place as it works for all other apps but it's fixed now and you can update Rift downgrader to enjoy downgrading again. If this issue comes back feel free to reopen this issue
